# Generated by Django 4.2.3 on 2023-07-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metainfo",
            name="iRacing_password",
            field=models.CharField(default="test@gmail.com", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metainfo",
            name="iRacing_username",
            field=models.EmailField(default="admin123", max_length=254),
            preserve_default=False,
        ),
    ]
