# Generated by Django 4.2.3 on 2023-07-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_metainfo_iracing_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metainfo",
            name="iRacing_password",
            field=models.CharField(max_length=255),
        ),
    ]
